const app=document.querySelector('#app');
const SAVE='cronicas-promessa-save-v2';
const tribes=['Rúben','Simeão','Levi','Judá','Dã','Naftali','Gade','Aser','Issacar','Zebulom','José','Benjamim'];
const vocations=['Pastor','Agricultor','Coletor','Levita'];
let state={profile:null,x:900,y:980,day:1,time:480,inventory:{},reputation:0};
const load=()=>{try{const s=localStorage.getItem(SAVE);if(s)state={...state,...JSON.parse(s)}}catch{}};
const save=()=>localStorage.setItem(SAVE,JSON.stringify(state)); load();
const isTouch=()=>matchMedia('(pointer:coarse)').matches;
function menu(){app.innerHTML=`<main class="screen"><section class="panel"><h1 class="title">CRÔNICAS DA PROMESSA</h1><p class="subtitle">Um povo em caminho. Muitas histórias para viver.</p><div class="menu"><button class="btn" id="new">NOVA JORNADA</button><button class="btn secondary" id="continue" ${state.profile?'':'disabled'}>CONTINUAR</button></div><p class="subtitle">Web Alpha 0.2 • Judá jogável</p></section></main>`;new.onclick=create;document.querySelector('#continue').onclick=game}
function create(){app.innerHTML=`<main class="screen"><section class="panel"><h2 class="title" style="font-size:36px">SUA JORNADA COMEÇA AQUI</h2><div class="form"><label>NOME<input id="name" maxlength="22" placeholder="Seu nome"/></label><div class="row"><label>PERSONAGEM<select id="sex"><option>Masculino</option><option>Feminino</option></select></label><label>TRIBO DE ISRAEL<select id="tribe">${tribes.map(t=>`<option ${t==='Judá'?'selected':''}>${t}</option>`).join('')}</select></label></div><label>VOCAÇÃO<select id="vocation">${vocations.map(v=>`<option>${v}</option>`).join('')}</select></label><div class="row"><button class="btn secondary" id="back">VOLTAR</button><button class="btn" id="start">INICIAR JORNADA</button></div></div></section></main>`;back.onclick=menu;start.onclick=()=>{const n=name.value.trim();if(!n)return name.focus();state={profile:{name:n,sex:sex.value,tribe:tribe.value,vocation:vocation.value},x:900,y:980,day:1,time:480,inventory:{},reputation:0};save();game()}}
function game(){if(!state.profile)return create();
app.innerHTML=`<main class="game"><div class="world" id="world">
<div class="zone standard-zone">TENDA DO ESTANDARTE</div><div class="zone council-zone">CONSELHO</div><div class="zone family-zone">TENDAS FAMILIARES</div><div class="zone corral-zone">CURRAIS</div><div class="zone workshop-zone">OFICINAS</div>
<div class="path main-v"></div><div class="path main-h"></div><div class="court"></div>
<div class="tent standard" style="left:780px;top:105px"></div><div class="tent" style="left:350px;top:270px"></div><div class="tent" style="left:1190px;top:250px"></div><div class="tent" style="left:1370px;top:360px"></div>
<div class="fire" style="left:875px;top:555px"></div><div class="well" style="left:855px;top:790px"></div>
<div class="prop" style="left:290px;top:700px">🐑</div><div class="prop" style="left:390px;top:740px">🐐</div><div class="prop" style="left:1280px;top:720px">⚒</div>
<div class="player" id="player"></div></div>
<div class="hud"><b>${state.profile.name}</b> • Tribo de ${state.profile.tribe} • ${state.profile.vocation}<br>Dia ${state.day} • <span id="clock"></span> • Rep. <span id="rep">${state.reputation}</span></div>
<div class="objective" id="objective">Objetivo: vá até a fogueira central.</div><div class="prompt hidden" id="prompt"></div><button class="game-menu" id="gameMenu">☰</button>
<div class="touch hidden" id="touch"><button data-k="w">▲</button><div><button data-k="a">◀</button><button data-k="s">▼</button><button data-k="d">▶</button></div></div><button class="action hidden" id="action">AÇÃO</button><div class="badge">Web Alpha 0.2</div></main>`;
const world=document.querySelector('#world'),p=document.querySelector('#player'),prompt=document.querySelector('#prompt'),keys=new Set(),touch=document.querySelector('#touch'),action=document.querySelector('#action'); if(isTouch())touch.classList.remove('hidden');
let near=false,done=false;
function interact(){if(!near)return; if(!done){done=true;state.reputation+=2;state.inventory.lenha=(state.inventory.lenha||0)+1;save();document.querySelector('#rep').textContent=state.reputation;document.querySelector('#objective').textContent='Objetivo concluído: você conheceu o pátio central.';prompt.textContent='+1 Lenha • Reputação +2'}else prompt.textContent='A fogueira aquece o pátio de Judá.'}
function draw(){p.style.left=state.x+'px';p.style.top=state.y+'px';world.style.transform=`translate(${innerWidth/2-state.x}px,${innerHeight/2-state.y}px)`;near=Math.hypot(state.x-900,state.y-590)<105;prompt.classList.toggle('hidden',!near);action.classList.toggle('hidden',!near||!isTouch());if(near&&!done)prompt.textContent=isTouch()?'AÇÃO — Examinar fogueira':'E — Examinar fogueira';const h=Math.floor(state.time/60)%24,m=Math.floor(state.time%60);clock.textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
const down=e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e')interact();if(e.key==='Escape'){save();menu()}};const up=e=>keys.delete(e.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);action.onclick=interact;gameMenu.onclick=()=>{save();menu()};
touch.querySelectorAll('button').forEach(b=>{const k=b.dataset.k;const on=e=>{e.preventDefault();keys.add(k)},off=e=>{e.preventDefault();keys.delete(k)};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)});
let last=performance.now();function tick(now){if(!document.body.contains(p)){removeEventListener('keydown',down);removeEventListener('keyup',up);return}const dt=Math.min((now-last)/16.67,2);last=now;let dx=0,dy=0;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(dx||dy){const l=Math.hypot(dx,dy);state.x=Math.max(70,Math.min(1690,state.x+dx/l*4.2*dt));state.y=Math.max(70,Math.min(1090,state.y+dy/l*4.2*dt));state.time+=.04*dt}draw();requestAnimationFrame(tick)}draw();requestAnimationFrame(tick)}
menu();